USER_ID_FIELD: user_id
ITEM_ID_FIELD: item_id
LABEL_FIELD: label_id
TIME_FIELD: timestamp
field_separator: "\t"
load_col:
  inter: [user_id, item_id, timestamp, label_id]

# user_id_field: user_id
# item_id_field: item_id
# field_separator: "\t"
# load_col:
#   inter: [user_id, item_id, timestamp]
# dataset: steam