#!/bin/bash

#SBATCH --partition=gpu_a100
#SBATCH --gpus=1
#SBATCH --job-name=steam_MVAE
#SBATCH --time=0:59:00
#SBATCH --output=./slurm_out/steam/MVAE.out

#exit if an error occurs
set -e

module purge
module load 2024
module load Miniconda3/24.7.1-0
module load CUDA/12.6.0

source activate recbole

cd ~/RecBole/

sed -i '1s/product_id/item_id/' dataset/steam/steam.inter
python run_recbole.py --model=MultiVAE --config_files=recbole/config/steam.yaml

echo "Done"