#!/bin/bash

#SBATCH --partition=gpu_a100
#SBATCH --gpus=1
#SBATCH --job-name=ml1m_test
#SBATCH --time=01:00:00
#SBATCH --output=./slurm_out/steam/test_ml1m_%A.out

#exit if an error occurs
set -e

module purge
module load 2024
module load Miniconda3/24.7.1-0
module load CUDA/12.6.0

source activate inf-ae

cd /home/scur2760/inf-ae_team_1/RecBole

echo "Running Ranking Metrics"

python run_recbole.py \
  --model=NeuMF \
  --config_files=recbole/config/ml-1m.yaml \
  --metrics="[\"Recall\", \"MRR\", \"NDCG\", \"Precision\", \"Hit\", \"MMF\", \"MMF_10c\", \"GiniIndex\"]" \
  --topk="[10, 100]" \
  --dataset=ml-1m \

echo "Done"