#!/bin/bash

#SBATCH --partition=gpu_a100
#SBATCH --gpus=1
#SBATCH --job-name=install_db
#SBATCH --time=0:59:00
#SBATCH --output=./slurm_out/install_db.out

#exit if an error occurs
set -e

module purge
module load 2024
module load Miniconda3/24.7.1-0
module load CUDA/12.6.0

source activate recbole

cd ~/

git clone https://github.com/RUCAIBox/RecDatasets

echo "Installed RecDatasets"

cd RecDatasets/conversion_tools

pip install -r requirements.txt